INSERT INTO "travel_item" ("title", "weight", "quantity", "season", "distance")
VALUES('Tent: REI Co-op Half Dome 2 Plus', 2.27, 1, 'SUMMER', 10),
('Sleeping Pad: Therm-a-Rest NeoAir Xlite', 0.34, 1, 'SUMMER', 10 ),
('First Aid Kit: Adventure Medical Kits Ultralight/Watertight .5', 0.1, 1, 'SUMMER', 10),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 10),
('Water', 1, 2, 'SUMMER', 10),
('Map and Compass', 0.14, 1, 'SUMMER', 10),
('Clothing (extra set): Lightweight jacket, extra socks, hat', 0.91, 1, 'SUMMER', 20),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 20),
('Water', 1, 1, 'SUMMER', 20),
('Stove: MSR PocketRocket 2', 0.07, 1, 'SUMMER', 30),
('Cookware: GSI Outdoors Pinnacle Soloist Cookset', 0.31, 1, 'SUMMER', 30),
('Water Filtration: Sawyer Squeeze Water Filter', 0.09, 1, 'SUMMER', 30),
('Headlamp: Black Diamond Spot Headlamp', 0.09, 1, 'SUMMER', 30),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 30),
('Water', 1, 1, 'SUMMER', 30),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 40),
('Water', 1, 1, 'SUMMER', 40),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 50),
('Water', 1, 1,  'SUMMER', 50),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 60),
('Water', 1, 1, 'SUMMER', 60),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 70),
('Water', 1, 1, 'SUMMER', 70),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 80),
('Water', 1, 1, 'SUMMER', 80),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 90),
('Water', 1, 1, 'SUMMER', 90),
('Food: energy bars, dried fruits, and dehydrated meals', 0.9, 1, 'SUMMER', 100),
('Water', 1, 1, 'SUMMER', 100);
